stages:
  - test
  - qa
  - deploy

before_script:
  - mkdir datasets

test_python:
  tags:
    - my_runner
  image: python:3.7
  stage: test
  script:
  - pip3 install tox
  - tox -e py37
  artifacts:
    paths:
      - htmlcov

qa_lint:
  tags:
    - my_runner
  image: python:3.7
  stage: qa
  script:
  - pip3 install tox
  - tox -e lint

pages:
  tags:
    - my_runner
  stage: deploy
  dependencies:
    - test_python
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
