include:
  - template: Secret-Detection.gitlab-ci.yml

stages:
  - secret_detection
  - test
  - qa
  - deploy

before_script:
  - mkdir datasets

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

test_python:
  image: python:3.7
  stage: test
  script:
  - pip3 install tox
  - tox -e py37
  artifacts:
    paths:
      - htmlcov

qa_lint:
  image: python:3.7
  stage: qa
  script:
  - pip3 install tox
  - tox -e lint

pages:
  stage: deploy
  dependencies:
    - test_python
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
