stages:
  - test
  - qa

before_script:
  - mkdir datasets

test_python:
  image: python:3.7
  stage: test
  script:
  - pip3 install tox
  - tox -e py37
  artifacts:
    paths:
      - htmlcov

qa_lint:
  image: python:3.7
  stage: qa
  script:
  - pip3 install tox
  - tox -e lint
